[launcher]
version = 1.0.0
description = USM Snyk Add-on
author = USM

[id]
version = 1.0.0
name = TA-usm-snyk-addon

[install]
build = 1785195622
is_configured = false
state = enabled

[package]
id = TA-usm-snyk-addon
check_for_updates = true

[ui]
label = USM Snyk Add-on
supported_themes = light, dark
is_visible = true

[triggers]
reload.ta_usm_snyk_addon_settings = simple
reload.ta_usm_snyk_addon_account = simple
