[admin:TA_usm_snyk_addon_configuration]
match = /
members = TA_usm_snyk_addon_account, TA_usm_snyk_addon_settings

[admin:TA_usm_snyk_addon_inputs]
match = /
members = TA_usm_snyk_addon_snyk_audit_logs

[admin_external:TA_usm_snyk_addon_account]
handlertype = python
python.version = python3
handlerfile = TA_usm_snyk_addon_rh_account.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:TA_usm_snyk_addon_settings]
handlertype = python
python.version = python3
handlerfile = TA_usm_snyk_addon_rh_settings.py
handleractions = edit, list
handlerpersistentmode = true

[admin_external:TA_usm_snyk_addon_snyk_audit_logs]
handlertype = python
python.version = python3
handlerfile = TA_usm_snyk_addon_rh_snyk_audit_logs.py
handleractions = edit, list, remove, create
handlerpersistentmode = true
