[expose:TA_usm_snyk_addon_account]
pattern = TA_usm_snyk_addon_account
methods = POST, GET

[expose:TA_usm_snyk_addon_account_specified]
pattern = TA_usm_snyk_addon_account/*
methods = POST, GET, DELETE

[expose:TA_usm_snyk_addon_settings]
pattern = TA_usm_snyk_addon_settings
methods = POST, GET

[expose:TA_usm_snyk_addon_settings_specified]
pattern = TA_usm_snyk_addon_settings/*
methods = POST, GET, DELETE

[expose:TA_usm_snyk_addon_snyk_audit_logs]
pattern = TA_usm_snyk_addon_snyk_audit_logs
methods = POST, GET

[expose:TA_usm_snyk_addon_snyk_audit_logs_specified]
pattern = TA_usm_snyk_addon_snyk_audit_logs/*
methods = POST, GET, DELETE

[expose:TA_usm_snyk_addon_snyk_issues]
pattern = TA_usm_snyk_addon_snyk_issues
methods = POST, GET

[expose:TA_usm_snyk_addon_snyk_issues_specified]
pattern = TA_usm_snyk_addon_snyk_issues/*
methods = POST, GET, DELETE

[expose:TA_usm_snyk_addon_snyk_projects]
pattern = TA_usm_snyk_addon_snyk_projects
methods = POST, GET

[expose:TA_usm_snyk_addon_snyk_projects_specified]
pattern = TA_usm_snyk_addon_snyk_projects/*
methods = POST, GET, DELETE

[expose:data/indexes]
pattern = data/indexes
methods = GET
